# .goreleaser.yml
# Build customization
builds:
  - binary: stern
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s 
      - -w
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
